spring:
    datasource:
        hikari:
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000

mysql:
    local:
        url: "jdbc:mysql://127.0.0.1:3306/user?useSSL=false"
        username: "root"
        password: "123456"
    local2:
        url: "jdbc:mysql://127.0.0.1:3306/mock?useSSL=false"
        username: "root"
        password: "123456"

knife4j:
    enable: true
#    documents:
#        -
#            group: 2.X版本
#            name: 接口签名
#            locations: classpath:com/ms/controller/*
#    setting:
#        language: zh_cn
#        enable-swagger-models: true
#        enable-document-manage: true
#        swagger-model-name: 实体类列表
#        enable-version: false
#        enable-reload-cache-parameter: false
#        enable-after-script: true
#        enable-filter-multipart-api-method-type: POST
#        enable-filter-multipart-apis: false
#        enable-request-cache: true
#        enable-host: false
#        enable-host-text: 192.168.0.193:8000
#        enable-home-custom: true
#        home-custom-path: classpath:markdown/home.md
#        enable-search: false
#        enable-footer: false
#        enable-footer-custom: true
#        footer-custom-content: Apache License 2.0 | Copyright  2019-[浙江八一菜刀股份有限公司](https://gitee.com/xiaoym/knife4j)
#        enable-dynamic-parameter: false
#        enable-debug: true
#        enable-open-api: false
#        enable-group: true
#    cors: false
#    production: false
#    basic:
#        enable: false
#        username: test
#        password: 12313